name: Build

on: push

jobs:
  test:
    runs-on: ${{ matrix.architecture.os }}
    strategy:
      matrix:
        rust: [stable]
        architecture: [
            {os: ubuntu-latest, target: "x86_64-unknown-linux-gnu"},
            {os: macOS-latest, target: "x86_64-apple-darwin"},
            {os: macOS-latest, target: "aarch64-apple-darwin"},
            {os: windows-latest, target: "x86_64-pc-windows-msvc"},
        ]
    steps:
      - name: "Checkout Repo"
        uses: actions/checkout@v4
      - name: "Install Rust"
        uses: dtolnay/rust-toolchain@stable
        with:
          target: ${{ matrix.architecture.target }}
      - name: Build the crate for release
        run: cargo build --release --features emacs
      - name: Run tests
        if: matrix.architecture.os != 'windows-latest'
        run: cargo test --verbose
