name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ${{matrix.architecture.os}}
    strategy:
      matrix:
        rust: [stable]
        architecture: [
            {os: ubuntu-latest, target: "x86_64-unknown-linux-gnu"},
            {os: macOS-latest, target: "x86_64-apple-darwin"},
            {os: macOS-latest, target: "aarch64-apple-darwin"},
            {os: windows-latest, target: "x86_64-pc-windows-msvc"},
        ]
        include:
          - architecture.os: macOS-latest
            rust: stable
            artifact_name: libparinfer_rust.dylib
            release_name: parinfer-rust-darwin.so
          - architecture.os: windows-latest
            rust: stable
            artifact_name: parinfer_rust.dll
            release_name: parinfer-rust-windows.dll
          - architecture.os: ubuntu-latest
            rust: stable
            artifact_name: libparinfer_rust.so
            release_name: parinfer-rust-linux.so
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          target: ${{ matrix.architecture.target  }}
      - name: Build the crate for release
        run: cargo build --release --target ${{ matrix.architecture.target }} --features emacs
      - name: Run tests
        if: matrix.architecture.os != 'windows-latest'
        run: cargo test --verbose
      - name: Rename library
        run: cp target/${{ matrix.architecture.target }}/release/${{ matrix.artifact_name }} ${{ matrix.release_name }}
      - name: Upload libraries to GitHub release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ${{ matrix.release_name }}
